"""empty message

Revision ID: 0a8cfc178244
Revises: cb75b53f3995
Create Date: 2022-06-21 15:53:18.393953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a8cfc178244'
down_revision = 'cb75b53f3995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_profile', sa.Column('country', sa.Text(), nullable=True))
    op.add_column('account_profile', sa.Column('language', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account_profile', 'language')
    op.drop_column('account_profile', 'country')
    # ### end Alembic commands ###
