"""empty message

Revision ID: 21c6c98e272c
Revises: 7cc970ebd9f9
Create Date: 2022-04-30 18:41:25.717132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21c6c98e272c'
down_revision = '7cc970ebd9f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_picture', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='varchar'), nullable=True),
    sa.Column('marital_status', sa.Enum('single', 'married', 'divorced', 'widowed', name='varchar'), nullable=True),
    sa.Column('education', sa.Enum('undergraduate', 'graduate', 'post_graduate', name='varchar'), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userprofile_account_id'), 'userprofile', ['account_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userprofile_account_id'), table_name='userprofile')
    op.drop_table('userprofile')
    op.drop_table('user_roles')
    # ### end Alembic commands ###
