"""empty message

Revision ID: 6f7be069d907
Revises: 0a8cfc178244
Create Date: 2022-07-28 18:10:08.615651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f7be069d907'
down_revision = '0a8cfc178244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_name', sa.String(length=100), nullable=True),
    sa.Column('course', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expertise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('social_media_type', sa.String(length=100), nullable=True),
    sa.Column('social_media_link', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_education',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('education_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account_profile.id'], ),
    sa.ForeignKeyConstraint(['education_id'], ['education.id'], ),
    sa.PrimaryKeyConstraint('id', 'account_id', 'education_id')
    )
    op.create_table('account_expertise',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('expertise_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account_profile.id'], ),
    sa.ForeignKeyConstraint(['expertise_id'], ['expertise.id'], ),
    sa.PrimaryKeyConstraint('id', 'account_id', 'expertise_id')
    )
    op.create_table('account_socialmedia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('social_media_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account_profile.id'], ),
    sa.ForeignKeyConstraint(['social_media_id'], ['social_media.id'], ),
    sa.PrimaryKeyConstraint('id', 'account_id', 'social_media_id')
    )
    op.create_table('account_workexperience',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('work_experience_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account_profile.id'], ),
    sa.ForeignKeyConstraint(['work_experience_id'], ['work_experience.id'], ),
    sa.PrimaryKeyConstraint('id', 'account_id', 'work_experience_id')
    )
    op.drop_index('ix_account_profile_account_id', table_name='account_profile')
    op.create_unique_constraint(None, 'account_profile', ['account_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account_profile', type_='unique')
    op.create_index('ix_account_profile_account_id', 'account_profile', ['account_id'], unique=False)
    op.drop_table('account_workexperience')
    op.drop_table('account_socialmedia')
    op.drop_table('account_expertise')
    op.drop_table('account_education')
    op.drop_table('work_experience')
    op.drop_table('social_media')
    op.drop_table('expertise')
    op.drop_table('education')
    # ### end Alembic commands ###
