"""empty message

Revision ID: 7cc970ebd9f9
Revises: 4b1eea651a69
Create Date: 2022-04-30 17:52:07.709688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cc970ebd9f9'
down_revision = '4b1eea651a69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('account', sa.Column('kyc_level', sa.String(length=100), nullable=False))
    op.add_column('account', sa.Column('role_id', sa.Integer(), nullable=False))
    op.add_column('account', sa.Column('registered_through', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'account', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.drop_column('account', 'registered_through')
    op.drop_column('account', 'role_id')
    op.drop_column('account', 'kyc_level')
    op.drop_table('role')
    # ### end Alembic commands ###
