"""empty message

Revision ID: a1fe3a879620
Revises: 21c6c98e272c
Create Date: 2022-04-30 19:01:45.570616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1fe3a879620'
down_revision = '21c6c98e272c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_picture', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='varchar'), nullable=True),
    sa.Column('marital_status', sa.Enum('single', 'married', 'divorced', 'widowed', name='varchar'), nullable=True),
    sa.Column('education', sa.Enum('undergraduate', 'graduate', 'post_graduate', name='varchar'), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_profile_account_id'), 'account_profile', ['account_id'], unique=True)
    op.drop_index('ix_userprofile_account_id', table_name='userprofile')
    op.drop_table('userprofile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userprofile',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_picture', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('marital_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('education', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name='userprofile_account_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='userprofile_pkey')
    )
    op.create_index('ix_userprofile_account_id', 'userprofile', ['account_id'], unique=False)
    op.drop_index(op.f('ix_account_profile_account_id'), table_name='account_profile')
    op.drop_table('account_profile')
    # ### end Alembic commands ###
